---
abstract: 'Interface to the New York City Subway.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0505, CPAN::Meta::Converter version 2.143240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Map-Tube-NYC
no_index:
  directory:
    - t
    - inc
provides:
  Map::Tube::NYC:
    file: lib/Map/Tube/NYC.pm
    version: '0.09'
  Map::Tube::NYC::Line::INDEighthAvenue:
    file: lib/Map/Tube/NYC/Line/INDEighthAvenue.pm
    version: '0.09'
requires:
  File::Share: '0'
  File::ShareDir::Install: '0'
  Map::Tube: '2.57'
  Moo: '0'
  namespace::clean: '0'
  perl: '5.006'
resources:
  repository: https://github.com/Manwar/Map-Tube-NYC.git
version: '0.09'

